# Generated by Django 5.1.7 on 2025-04-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='destination',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='registration',
            name='package',
            field=models.CharField(choices=[('budget', 'Budget'), ('standard', 'Standard'), ('luxury', 'Luxury')], max_length=10),
        ),
    ]
